{
    "name": "Hotel Base",
    "summary": "Properties, floors, room types, rooms, guests and agencies",
    "version": "19.0.1.0.0",
    "category": "Hotel Management",
    "author": "HEMFA",
    "license": "OPL-1",
    "depends": ["base", "mail", "product", "contacts"],
    "data": [
        "security/hotel_security.xml",
        "security/ir.model.access.csv",
        "views/hotel_property_views.xml",
        "views/hotel_floor_views.xml",
        "views/hotel_room_type_views.xml",
        "views/hotel_amenity_views.xml",
        "views/hotel_room_views.xml",
        "views/res_partner_views.xml",
        "views/hotel_menus.xml",
    ],
    "demo": [
        "demo/hotel_demo.xml",
    ],
    "application": True,
    "installable": True,
}
