{
    "name": "Hotel Folios",
    "summary": "Folio ledger, charge routing matrix, deposits, guest/entity/group invoicing",
    "version": "19.0.4.0.0",
    "category": "Hotel Management",
    "author": "HEMFA",
    "license": "OPL-1",
    "depends": ["hotel_reservation", "account"],
    "data": [
        "security/hotel_accounting_security.xml",
        "security/hotel_record_rules.xml",
        "security/ir.model.access.csv",
        "data/hotel_folio_sequence.xml",
        "wizard/hotel_finance_wizard_views.xml",
        "views/hotel_account_views.xml",
        "views/hotel_folio_views.xml",
        "views/hotel_group_folio_views.xml",
        "views/hotel_reservation_views.xml",
    ],
    "installable": True,
}
